version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}  # MongoDB Atlas URI
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PYTHONBUFFERED: 1
      CONNECTION_TRIES: ${CONNECTION_TRIES}
      EXPIRATION_MINUTES: ${EXPIRATION_MINUTES}
      SECRET_KEY: ${SECRET_KEY}
      PAGE_SIZE: ${PAGE_SIZE}
      MAX_IMAGE_SIZE: ${MAX_IMAGE_SIZE}
    volumes:
      - ./api:/api
