version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PYTHONBUFFERED: 1
      CONNECTION_TRIES: ${CONNECTION_TRIES}
      EXPIRATION_MINUTES: ${EXPIRATION_MINUTES}
      SECRET_KEY: ${SECRET_KEY}
      PAGE_SIZE: ${PAGE_SIZE}
      MAX_IMAGE_SIZE: ${MAX_IMAGE_SIZE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_AUTH_URL: ${GOOGLE_AUTH_URL}
      GOOGLE_TOKEN_URL: ${GOOGLE_TOKEN_URL}
      GOOGLE_USER_INFO_URL: ${GOOGLE_USER_INFO_URL}

    volumes:
      - ./src:/src
